<?php

// Set the timezone to your desired timezone
date_default_timezone_set('UTC');

// Define the directory where the static files will be generated
$outputDir = __DIR__ . '/output';

// Check if the output directory exists, and create it if it doesn't
if (!file_exists($outputDir)) {
    mkdir($outputDir, 0777, true);
}

// Example: Generate an HTML file as a static page
$htmlContent = "<html><head><title>My Static Page</title></head><body>";
$htmlContent .= "<h1>Welcome to My Static Page!</h1>";
$htmlContent .= "<p>This page was generated by the build script.</p>";
$htmlContent .= "<footer>Generated on " . date('Y-m-d H:i:s') . "</footer>";
$htmlContent .= "</body></html>";

// Define the output file path
$outputFile = $outputDir . '/index.html';

// Write the generated HTML content to the file
file_put_contents($outputFile, $htmlContent);

// Example: If you need to copy assets like images, CSS, or JavaScript, do it here
// For example, copying a CSS file:
if (file_exists(__DIR__ . '/assets/style.css')) {
    copy(__DIR__ . '/assets/style.css', $outputDir . '/style.css');
}

// You can also add more logic to generate other types of files or content here.

// Output a message indicating that the build was successful
echo "Static files have been generated successfully at: " . $outputDir . "\n";
